### ISSUE TITLE
Move This Here cause game crash

### ISSUE THREAD

**Issue by laiyoi** [DoctorFeelGoodMD/OxygenNotIncluded-Mods#17] opened 2024-05-03 18:10 UTC
When i build the Hauling Point the game crash.
I have tried this with other mods unenabled.
This is what logs say:
```
[18:04:15.602] [1] [ERROR] HaulingPointComplete UnityEngine.GameObject 'HaulingPointComplete' requires a component of type Deconstructable as requested by Reconstructable
```
Full logs is here:
[Player.log](https://github.com/DoctorFeelGoodMD/OxygenNotIncluded-Mods/files/15203533/Player.log)

**Comment by DoctorFeelGoodMD** [comment] 2024-05-03 20:02
This bug was caused by a game update and was resolved with the latest version of the mod - make sure you're updated to version 1.7.

**Closed as completed** 2024-12-06 12:18 UTC
